-- Create books table
create table public.books (
    id bigint generated by default as identity primary key,
    title text not null,
    author text not null,
    cover_image text not null,
    description text not null,
    price decimal(10,2) not null,
    display_order integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert sample books with order
insert into public.books (title, author, cover_image, description, price, display_order) values
(
    'Xaricdə Təhsil Rehberi',
    'Tural Həsənli',
    '/images/books/81i4ZDFgVoL._AC_UF1000,1000_QL80_.jpg',
    'Xaricdə təhsil almaq istəyənlər üçün ətraflı məlumat və təcrübə paylaşımı. Viza, sənəd hazırlığı və universitet seçimi haqqında məsləhətlər.',
    29.99,
    1
),
(
    'Avropada Yaşam və İş İmkanları',
    'Rəşad Nəsirov',
    '/images/books/1f9de821305419.562fef4167ab9.jpg',
    'Avropada yaşamaq və işləmək istəyənlər üçün tam bələdçi. İş axtarışı, CV hazırlığı və müsahibə məsləhətləri.',
    34.99,
    2
),
(
    'Xaricdə Ucuz Yaşamın Sirləri',
    'Tural Həsənli',
    '/images/books/tecrit-3d-03-scaled.jpg',
    'Xaricdə yaşayarkən büdcənizi idarə etmək üçün praktik məsləhətlər. Qənaət üsulları və maliyyə planlaması.',
    24.99,
    3
),
(
    'Səyahət Bloqçuluğu',
    'Rəşad Nəsirov',
    '/images/books/a1961a72ff28_1x (1).jpg',
    'Səyahət bloqçusu olmaq və sosial mediada uğur qazanmaq üçün ətraflı bələdçi. Kamera seçimindən kontentə qədər.',
    19.99,
    4
); 