-- Create featured_books table
create table public.featured_books (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    cover_image text not null,
    price decimal(10,2) not null,
    features text[] not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert sample featured book
insert into public.featured_books (title, description, cover_image, price, features) values
(
    'Xaricdə Ucuz Yaşamın Sirləri',
    'Bu kitabda xaricdə yaşamaq və səyahət etmək üçün lazım olan bütün məlumatları tapacaqsınız',
    '/images/book-cover.jpg',
    5.00,
    ARRAY[
        '🛂 Viza prosesi üçün lazım olan bütün məlumatlar və sirlər',
        '✈️ Ən ucuz biletləri tapmağın asan yolları və püşkləri',
        '🏠 Hotel və Airbnb seçimi - qiymət/keyfiyyət balansı',
        '📱 Xaricdə internet problemi - ən sərfəli həll yolları',
        '🚇 Şəhər nəqliyyatından istifadə və pula qənaət etmək'
    ]
); 